title: SmartFollower & Tracker
description: Object Tracking, Obstacle Circumvention, and 2D reconstruction
theme: just-the-docs

url: https://mobile-robots-ugv.github.io/page_1.html # https://just-the-docs.github.io

remote_theme: just-the-docs/just-the-docs
math: mathjax

mermaid:
  version: "10.6.1"

aux_links:
  Tatwik Meesala: https://tatwik19.github.io/
  Prajjwal: https://robopod.in/
  Lu Yan Tan: https://www.linkedin.com/in/lu-yan-tan-4b5a27290/
